/**
 * mutation-types.js
 */

//news
export const GET_NEWSLIST = 'GET_NEWSLIST'
export const GET_ONE_NEWS = 'GET_ONE_NEWS'
export const CHANGE_LIST = 'CHANGE_LIST'
export const CHANGE_NEWS_ID = 'CHANGE_NEWS_ID'
export const CHANGE_NEWS_VIEW = 'CHANGE_NEWS_VIEW'

//goods
export const GET_GOODSLIST = 'GET_GOODSLIST'
export const GET_GOODS_CATE = 'GET_GOODS_CATE'
export const CHANGE_FILTER_CATE = 'CHANGE_FILTER_CATE'
export const CHANGE_GOODS_VIEW = 'CHANGE_GOODS_VIEW'

export const GET_ONE_GOODS = 'GET_ONE_GOODS'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const REDUCE_QUANTITY = 'REDUCE_QUANTITY'
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'

//cart
export const CHANGE_CART_LIST = 'CHANGE_CART_LIST'
export const DELETE_CART_LIST = 'DELETE_CART_LIST'
export const CART_ADD_QUANTITY = 'CART_ADD_QUANTITY'
export const CART_REDUCE_QUANTITY = 'CART_REDUCE_QUANTITY'
export const CART_INPUT_QUANTITY = 'CART_INPUT_QUANTITY'
export const CHANGE_ONCE_CHECKED = 'CHANGE_ONCE_CHECKED'
export const CHANGE_ALLCHECKED = 'CHANGE_ALLCHECKED'
export const CHANGE_TOTAL = 'CHANGE_TOTAL'
export const CHANGE_SELECTED = 'CHANGE_SELECTED'

//func
export const CHANGE_FUNC_LIST = 'CHANGE_FUNC_LIST'

//collection
export const CHANGE_COLLECTION = 'CHANGE_COLLECTION'
export const CHANGE_FILTER_COLLECTION = 'CHANGE_FILTER_COLLECTION'
